### ISSUE TITLE
installer improvements

### ISSUE THREAD

**Issue by PLaRoche** [toplog/toplog-forwarder-installer#14]
A few things:
- [x] Apparently we should be installing in /usr/local/ not /usr/bin
- [x] pick up on streams that exist all teh time (no need for `-a`) and add them to a list the user sees and can select from (sort of "we noticed you already have streams a, b, c, would you like to use one of them`)
- [ ] check if configs already exist on server and compare against users streams.  If no match, ask the user; "We detect outdated configs on this server, would you like us to clean them out for you (recommended)?"

**Comment by cameronevans** [comment]
proposed:
configs to
`/etc/logstash-forwarder/conf.d/`
binary to
`/usr/local/logstash-forwarder/`
logs to
`/var/log/logstash-forwarder/`

The only issue I could see would be if the user already had logstash-forwarder installed. Perhaps we could make these paths configurable?

**Comment by PLaRoche** [comment]
Some guidance, which comes from security stuff Apple is pushing out:

"The specifics of System Integrity Protection are that no user, application, or process will be able to write files or modify files in the root System folder or the /bin, /sbin, and /usr directories, which are hidden by default in OS X’s Finder. The /usr/local folder remains accessible, however; it’s a long-running convention in Unix and variants as a place to stash material and software that individual users rely on.

El Capitan will also remove files from those directories that don’t belong to Apple. Upgrading to El Capitan will therefore disable some software you want, but also pull out old cruft that isn’t needed, and perhaps kill some lurking horrors. Only Apple installer software and software updater can modify the contents of those folders."

So putting the binaries in `/usr/local/` seems to follow what they want people to do

**Comment by RyanNielson** [comment]
Ya, I'd say we default to those paths @cameronevans mentioned above but give them the option to change them in case they're already in use.
